test: off

environment:
  FILENAME: test.rar
  MSI_NAME: groupwise.msi
  DOWNLOAD_URL: https://storage.googleapis.com/cloudmigrator-automated-tests/test.rar
  FOLDER: C:\projects\appvtest
branches:
  only:
    - master

max_jobs: 1

install:
  - ps: |
      Write-Host "Hello, Build!" -BackgroundColor Yellow -ForegroundColor Black
      Write-Host (Get-Item -Path ".\").FullName
      Start-FileDownload $env:DOWNLOAD_URL
      get-childitem $env.FOLDER -recurse
  - 7z x C:\projects\appvtest\test.rar > nul
      get-childitem $env.FOLDER 
#      msiexec /i MSI_PATH /quiet /qn /norestart /log install.log