build: off
test: off

environment:
  GROUPWISE_FILENAME: 2018GWClient.zip
  GROUPWISE_MSI_NAME: groupwise.msi
  GROUPWISE_DOWNLOAD_URL: https://storage.googleapis.com/cloudmigrator-automated-tests/2018GWClient.zip
  FOLDER: C:\projects\appvtest\
  GROUPWISE_FILE_PATH: $(FOLDER)$(GROUPWISE_FILENAME)
  GROUPWISE_MSI_PATH: $(FOLDER)$(GROUPWISE_MSI_NAME)
  LOG_FILE: install.log
  LOG_PATH: $(FOLDER)$(LOG_FILE)
branches:
  only:
    - master

max_jobs: 1

install:
  - ps: |
      Write-Host "Hello, Build!" -BackgroundColor Yellow -ForegroundColor Black
      Start-FileDownload $env:GROUPWISE_DOWNLOAD_URL
  - 7z x %GROUPWISE_FILE_PATH% > nul
  - ps: |
      msiexec /i $env:GROUPWISE_MSI_PATH /quiet /qn /norestart /log install.log
      if(Test-Path -Path $env:LOG_PATH)
      {
        Write-Host "Log found"
        Push-AppveyorArtifact %LOG_PATH%
      }
artifacts:
  - path: C:\projects\appvtest\
    name: install
    type: log