test: off

environment:
  FILENAME: test.rar
  MSI_NAME: groupwise.msi
  RELATIVE_PATH: tools\
  FULL_FILE_PATH: $(RELATIVE_PATH)$(FILENAME)
  MSI_PATH: ${RELATIVE_PATH}$(MSI_NAME)
  DOWNLOAD_URL: https://storage.googleapis.com/cloudmigrator-automated-tests/test.rar

branches:
  only:
    - master

max_jobs: 1

install:
  - ps: |
      Write-Host "Hello, Build!" -BackgroundColor Yellow -ForegroundColor Black
      Write-Host $"(Test-Path -Path $env:FULL_FILE_PATH)"
      Start-FileDownload $env:DOWNLOAD_URL
      7z x %FILENAME% > nul
#      msiexec /i MSI_PATH /quiet /qn /norestart /log install.log