environment:
  GW_FILENAME: groupWise.zip
  GW_PATH: tools\
  GW_FULL_FILE_PATH: $(GW_PATH)$(GW_FILENAME)
  GW: https://bla-bla.bla

branches:
  only:
    - master

max_jobs: 1

install:
  - ps: |
      Write-Host "Hello, Build!" -BackgroundColor Yellow -ForegroundColor Black