init:      

# Using this we can block the shutdown of the VM and logon to investigate the craic
#  - ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

  - ps: |
      Write-Host "Hello, Build!" -BackgroundColor Yellow -ForegroundColor Black