test: off

environment:
  GROUPWISE_FILENAME: 2018GWClient.zip
  GROUPWISE_MSI_NAME: groupwise.msi
  GROUPWISE_DOWNLOAD_URL: https://storage.googleapis.com/cloudmigrator-automated-tests/2018GWClient.zip
  FOLDER: C:\projects\appvtest\

branches:
  only:
    - master

max_jobs: 1

install:
  - ps: |
      Write-Host "Hello, Build!" -BackgroundColor Yellow -ForegroundColor Black
      Write-Host (Get-Item -Path ".\").FullName
      Start-FileDownload $env:GROUPWISE_DOWNLOAD_URL
      get-childitem $env.FOLDER -recurse
  - 7z x $(FOLDER)$(GROUPWISE_FILENAME) > nul
  - ps: get-childitem $env.FOLDER 
  - ps: msiexec /i $(FOLDER)$(GROUPWISE_MSI_NAME) /quiet /qn /norestart /log install.log